" This VIMRC assumes the following Fedora RPMs are installed.
" vim-fugitive (noarch)
" vim-latex (noarch)
" vim-powerline (noarch)
" vim-jedi (noarch)
" vim-enhanced (x86_64)
" vim-nerdtree (noarch)
" vim-go (noarch)
"

set nocompatible

execute pathogen#infect()

let mapleader=","
set number
set laststatus=2
set showtabline=2
set noshowmode
set t_Co=16

let g:Tex_DefaultTargetFormat="pdf"

filetype plugin indent on

map <C-n> :NERDTreeToggle<CR>

function! CheckLeftBuffers()
  if tabpagenr('$') == 1
    let i = 1
    while i <= winnr('$')
      if getbufvar(winbufnr(i), '&buftype') == 'help' ||
          \ getbufvar(winbufnr(i), '&buftype') == 'quickfix' ||
          \ exists('t:NERDTreeBufName') &&
          \   bufname(winbufnr(i)) == t:NERDTreeBufName ||
          \ bufname(winbufnr(i)) == '__Tag_List__'
        let i += 1
      else
        break
      endif
    endwhile
    if i == winnr('$') + 1
      qall
    endif
    unlet i
  endif
endfunction
autocmd BufEnter * call CheckLeftBuffers()

if has("gui_running")
  set background=light
  colorscheme base16-chalk
  set guifont=Roboto\ Mono
endif

